development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: esonia_store_dev
  pool: 5
  username: rails_user
  password: mint06

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: esonia_store_test
  pool: 5
  username: rails_user
  password: mint06

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: esonia_store_production
  pool: 5
  username: rails_user
  password: mint06 